//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress.DevAV.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DevAVDbResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevAVDbResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevExpress.HybridApp.Localization.DevAVDbResources", typeof(DevAVDbResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

			        public static string Customer { get { return ResourceManager.GetString("Customer", resourceCulture); } }
		        public static string CustomerPlural { get { return ResourceManager.GetString("CustomerPlural", resourceCulture); } }
		        public static string Customer_Name { get { return ResourceManager.GetString("Customer_Name", resourceCulture); } }
		        public static string Customer_AddressState { get { return ResourceManager.GetString("Customer_AddressState", resourceCulture); } }
		        public static string Customer_AddressLine { get { return ResourceManager.GetString("Customer_AddressLine", resourceCulture); } }
		        public static string Customer_AddressCity { get { return ResourceManager.GetString("Customer_AddressCity", resourceCulture); } }
		        public static string Customer_AddressZipCode { get { return ResourceManager.GetString("Customer_AddressZipCode", resourceCulture); } }
		        public static string Customer_Phone { get { return ResourceManager.GetString("Customer_Phone", resourceCulture); } }
		        public static string Customer_Fax { get { return ResourceManager.GetString("Customer_Fax", resourceCulture); } }
		        public static string Customer_Website { get { return ResourceManager.GetString("Customer_Website", resourceCulture); } }
		        public static string Customer_AnnualRevenue { get { return ResourceManager.GetString("Customer_AnnualRevenue", resourceCulture); } }
		        public static string Customer_TotalStores { get { return ResourceManager.GetString("Customer_TotalStores", resourceCulture); } }
		        public static string Customer_TotalEmployees { get { return ResourceManager.GetString("Customer_TotalEmployees", resourceCulture); } }
		        public static string Customer_Status { get { return ResourceManager.GetString("Customer_Status", resourceCulture); } }
		        public static string Customer_Logo { get { return ResourceManager.GetString("Customer_Logo", resourceCulture); } }
		        public static string CustomerStore { get { return ResourceManager.GetString("CustomerStore", resourceCulture); } }
		        public static string CustomerStorePlural { get { return ResourceManager.GetString("CustomerStorePlural", resourceCulture); } }
		        public static string CustomerStore_AddressState { get { return ResourceManager.GetString("CustomerStore_AddressState", resourceCulture); } }
		        public static string CustomerStore_AddressLine { get { return ResourceManager.GetString("CustomerStore_AddressLine", resourceCulture); } }
		        public static string CustomerStore_AddressCity { get { return ResourceManager.GetString("CustomerStore_AddressCity", resourceCulture); } }
		        public static string CustomerStore_AddressZipCode { get { return ResourceManager.GetString("CustomerStore_AddressZipCode", resourceCulture); } }
		        public static string CustomerStore_State { get { return ResourceManager.GetString("CustomerStore_State", resourceCulture); } }
		        public static string CustomerStore_Phone { get { return ResourceManager.GetString("CustomerStore_Phone", resourceCulture); } }
		        public static string CustomerStore_Fax { get { return ResourceManager.GetString("CustomerStore_Fax", resourceCulture); } }
		        public static string CustomerStore_TotalEmployees { get { return ResourceManager.GetString("CustomerStore_TotalEmployees", resourceCulture); } }
		        public static string CustomerStore_SquereFootage { get { return ResourceManager.GetString("CustomerStore_SquereFootage", resourceCulture); } }
		        public static string CustomerStore_AnnualSales { get { return ResourceManager.GetString("CustomerStore_AnnualSales", resourceCulture); } }
		        public static string CustomerStore_CrestLarge { get { return ResourceManager.GetString("CustomerStore_CrestLarge", resourceCulture); } }
		        public static string CustomerStore_CrestSmall { get { return ResourceManager.GetString("CustomerStore_CrestSmall", resourceCulture); } }
		        public static string CustomerStore_Location { get { return ResourceManager.GetString("CustomerStore_Location", resourceCulture); } }
		        public static string CustomerStore_Customer { get { return ResourceManager.GetString("CustomerStore_Customer", resourceCulture); } }
		        public static string Order { get { return ResourceManager.GetString("Order", resourceCulture); } }
		        public static string OrderPlural { get { return ResourceManager.GetString("OrderPlural", resourceCulture); } }
		        public static string Order_InvoiceNumber { get { return ResourceManager.GetString("Order_InvoiceNumber", resourceCulture); } }
		        public static string Order_PONumber { get { return ResourceManager.GetString("Order_PONumber", resourceCulture); } }
		        public static string Order_OrderDate { get { return ResourceManager.GetString("Order_OrderDate", resourceCulture); } }
		        public static string Order_SaleAmount { get { return ResourceManager.GetString("Order_SaleAmount", resourceCulture); } }
		        public static string Order_ShippingAmount { get { return ResourceManager.GetString("Order_ShippingAmount", resourceCulture); } }
		        public static string Order_TotalAmount { get { return ResourceManager.GetString("Order_TotalAmount", resourceCulture); } }
		        public static string Order_ShipDate { get { return ResourceManager.GetString("Order_ShipDate", resourceCulture); } }
		        public static string Order_OrderTerms { get { return ResourceManager.GetString("Order_OrderTerms", resourceCulture); } }
		        public static string Order_Customer { get { return ResourceManager.GetString("Order_Customer", resourceCulture); } }
		        public static string Order_Employee { get { return ResourceManager.GetString("Order_Employee", resourceCulture); } }
		        public static string Order_Store { get { return ResourceManager.GetString("Order_Store", resourceCulture); } }
		        public static string Employee { get { return ResourceManager.GetString("Employee", resourceCulture); } }
		        public static string EmployeePlural { get { return ResourceManager.GetString("EmployeePlural", resourceCulture); } }
		        public static string Employee_FirstName { get { return ResourceManager.GetString("Employee_FirstName", resourceCulture); } }
		        public static string Employee_LastName { get { return ResourceManager.GetString("Employee_LastName", resourceCulture); } }
		        public static string Employee_Prefix { get { return ResourceManager.GetString("Employee_Prefix", resourceCulture); } }
		        public static string Employee_HomePhone { get { return ResourceManager.GetString("Employee_HomePhone", resourceCulture); } }
		        public static string Employee_MobilePhone { get { return ResourceManager.GetString("Employee_MobilePhone", resourceCulture); } }
		        public static string Employee_Email { get { return ResourceManager.GetString("Employee_Email", resourceCulture); } }
		        public static string Employee_Skype { get { return ResourceManager.GetString("Employee_Skype", resourceCulture); } }
		        public static string Employee_BirthDate { get { return ResourceManager.GetString("Employee_BirthDate", resourceCulture); } }
		        public static string Employee_Picture { get { return ResourceManager.GetString("Employee_Picture", resourceCulture); } }
		        public static string Employee_AddressState { get { return ResourceManager.GetString("Employee_AddressState", resourceCulture); } }
		        public static string Employee_AddressLine { get { return ResourceManager.GetString("Employee_AddressLine", resourceCulture); } }
		        public static string Employee_AddressCity { get { return ResourceManager.GetString("Employee_AddressCity", resourceCulture); } }
		        public static string Employee_AddressZipCode { get { return ResourceManager.GetString("Employee_AddressZipCode", resourceCulture); } }
		        public static string Employee_Department { get { return ResourceManager.GetString("Employee_Department", resourceCulture); } }
		        public static string Employee_Title { get { return ResourceManager.GetString("Employee_Title", resourceCulture); } }
		        public static string Employee_Status { get { return ResourceManager.GetString("Employee_Status", resourceCulture); } }
		        public static string Employee_HireDate { get { return ResourceManager.GetString("Employee_HireDate", resourceCulture); } }
		        public static string Employee_PersonalProfile { get { return ResourceManager.GetString("Employee_PersonalProfile", resourceCulture); } }
		        public static string Employee_Order { get { return ResourceManager.GetString("Employee_Order", resourceCulture); } }
		        public static string EmployeeTask { get { return ResourceManager.GetString("EmployeeTask", resourceCulture); } }
		        public static string EmployeeTaskPlural { get { return ResourceManager.GetString("EmployeeTaskPlural", resourceCulture); } }
		        public static string EmployeeTask_Subject { get { return ResourceManager.GetString("EmployeeTask_Subject", resourceCulture); } }
		        public static string EmployeeTask_Description { get { return ResourceManager.GetString("EmployeeTask_Description", resourceCulture); } }
		        public static string EmployeeTask_StartDate { get { return ResourceManager.GetString("EmployeeTask_StartDate", resourceCulture); } }
		        public static string EmployeeTask_DueDate { get { return ResourceManager.GetString("EmployeeTask_DueDate", resourceCulture); } }
		        public static string EmployeeTask_Status { get { return ResourceManager.GetString("EmployeeTask_Status", resourceCulture); } }
		        public static string EmployeeTask_Priority { get { return ResourceManager.GetString("EmployeeTask_Priority", resourceCulture); } }
		        public static string EmployeeTask_Completion { get { return ResourceManager.GetString("EmployeeTask_Completion", resourceCulture); } }
		        public static string EmployeeTask_Reminder { get { return ResourceManager.GetString("EmployeeTask_Reminder", resourceCulture); } }
		        public static string EmployeeTask_ReminderDateTime { get { return ResourceManager.GetString("EmployeeTask_ReminderDateTime", resourceCulture); } }
		        public static string EmployeeTask_AssignedEmployee { get { return ResourceManager.GetString("EmployeeTask_AssignedEmployee", resourceCulture); } }
		        public static string Quote { get { return ResourceManager.GetString("Quote", resourceCulture); } }
		        public static string QuotePlural { get { return ResourceManager.GetString("QuotePlural", resourceCulture); } }
		        public static string Quote_Number { get { return ResourceManager.GetString("Quote_Number", resourceCulture); } }
		        public static string Quote_Date { get { return ResourceManager.GetString("Quote_Date", resourceCulture); } }
		        public static string Quote_SubTotal { get { return ResourceManager.GetString("Quote_SubTotal", resourceCulture); } }
		        public static string Quote_ShippingAmount { get { return ResourceManager.GetString("Quote_ShippingAmount", resourceCulture); } }
		        public static string Quote_Total { get { return ResourceManager.GetString("Quote_Total", resourceCulture); } }
		        public static string Quote_Opportunity { get { return ResourceManager.GetString("Quote_Opportunity", resourceCulture); } }
		        public static string Quote_Customer { get { return ResourceManager.GetString("Quote_Customer", resourceCulture); } }
		        public static string Quote_CustomerStore { get { return ResourceManager.GetString("Quote_CustomerStore", resourceCulture); } }
		        public static string Quote_Employee { get { return ResourceManager.GetString("Quote_Employee", resourceCulture); } }
		        public static string Product { get { return ResourceManager.GetString("Product", resourceCulture); } }
		        public static string ProductPlural { get { return ResourceManager.GetString("ProductPlural", resourceCulture); } }
		        public static string Product_Name { get { return ResourceManager.GetString("Product_Name", resourceCulture); } }
		        public static string Product_Description { get { return ResourceManager.GetString("Product_Description", resourceCulture); } }
		        public static string Product_ProductionStart { get { return ResourceManager.GetString("Product_ProductionStart", resourceCulture); } }
		        public static string Product_Available { get { return ResourceManager.GetString("Product_Available", resourceCulture); } }
		        public static string Product_Image { get { return ResourceManager.GetString("Product_Image", resourceCulture); } }
		        public static string Product_CurrentInventory { get { return ResourceManager.GetString("Product_CurrentInventory", resourceCulture); } }
		        public static string Product_Backorder { get { return ResourceManager.GetString("Product_Backorder", resourceCulture); } }
		        public static string Product_Manufacturing { get { return ResourceManager.GetString("Product_Manufacturing", resourceCulture); } }
		        public static string Product_Barcode { get { return ResourceManager.GetString("Product_Barcode", resourceCulture); } }
		        public static string Product_Cost { get { return ResourceManager.GetString("Product_Cost", resourceCulture); } }
		        public static string Product_SalePrice { get { return ResourceManager.GetString("Product_SalePrice", resourceCulture); } }
		        public static string Product_RetailPrice { get { return ResourceManager.GetString("Product_RetailPrice", resourceCulture); } }
		        public static string Product_ConsumerRating { get { return ResourceManager.GetString("Product_ConsumerRating", resourceCulture); } }
		        public static string Product_Category { get { return ResourceManager.GetString("Product_Category", resourceCulture); } }
		        public static string Product_Engineer { get { return ResourceManager.GetString("Product_Engineer", resourceCulture); } }
		        public static string Product_Support { get { return ResourceManager.GetString("Product_Support", resourceCulture); } }
	
    }
}

