using DevExpress.Mvvm;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace DevExpress.DevAV {
    public abstract class DatabaseObject : IDataErrorInfo {
        /// <summary>
        /// Primary key property for all data model objects.
        /// See http://msdn.microsoft.com/en-us/data/jj679962.aspx for more details.
        /// </summary>
        [ScaffoldColumn(false)] // Indicates that Scaffolding Wizards should not generate UI for editing and displaying this property
        public long Id { get; set; }
        #region IDataErrorInfo
        string IDataErrorInfo.Error { get { return null; } }
        string IDataErrorInfo.this[string columnName]
        {
            get
            {
                // Obtains validation attributes applied to the corresponding property and combines error reports provided by them into one. 
                // Since the code generated by Scaffolding Wizards supports the IDataErrorInfo interface out of the box, the error is displayed in UI.
                // The Save command will also be disabled until all errors are fixed.
                // To learn more about the IDataErrorInfo support in Scaffolding Wizards, refer to the https://documentation.devexpress.com/#WPF/CustomDocument17157 topic
                return IDataErrorInfoHelper.GetErrorText(this, columnName);
            }
        }
        #endregion
    }
}
